image: docker:19.03.12

variables:

  CONTAINER_IMAGE: "vapprtech/crm:latest"

  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

stages:          # List of stages for jobs, and their order of execution
  - build_image
  - deploy_arrivnow-dev
  - deploy_arrivnow-qa


docker-build-image:
  stage: build_image
  script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker images
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} vapprtech/crm:latest
    - docker push ${CONTAINER_IMAGE}
  when: always
  only: 
    - develop


deploy-arrivnow-dev:
  stage: deploy_arrivnow-dev
  #needs: ["docker-build-image"]
  image: vapprtech/awskubectl:latest
  before_script:
    #- The below cluster name would be updated per branch based on some condition
    
    - aws eks update-kubeconfig --name arrivnow-dev --region us-east-2 

    - kubectl create namespace crm-content --dry-run=client -o yaml | kubectl apply -f -   
  script:
     # - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" manifest/crmdeployment.yaml
      - kubectl apply -f manifest
      - kubectl rollout restart deployment crm-content -n crm-content
      - kubectl get pods -n crm-content 
      - kubectl get svc -n crm-content -o wide
  when: always
  only: 
    - develop

deploy-arrivnow-qa:
  stage: deploy_arrivnow-qa
  #needs: ["docker-build-image"]
  image: vapprtech/awskubectl:latest
  before_script:
    #- The below cluster name would be updated per branch based on some condition
    
    - aws eks update-kubeconfig --name arrivnow-qa --region us-east-2 

    - kubectl create namespace crm-content --dry-run=client -o yaml | kubectl apply -f -   
  script:
     # - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" manifest/crmdeployment.yaml
      - kubectl apply -f manifest
      - kubectl rollout restart deployment crm-content -n crm-content
      - kubectl get pods -n crm-content 
      - kubectl get svc -n crm-content -o wide
  when: always
  only: 
    - staging    

