stages:
  - build
  - deploy

build:
   stage: build
   only:    
       - tags     
   script:
      - mkdir -p dist
      - npm install react-dates --legacy-peer-deps 
      - CI= npm run build
      - ls
      - echo "Build Successfully"
   artifacts:
       paths:
         - build/
       expire_in: 1 hour    
   only:
     - master


deploy:
   stage: deploy
   image:
     name: amazon/aws-cli
     entrypoint: [""]
   dependencies:
     - build
   script:
     - aws --version
     - aws s3 sync ./build s3://g4s-bucket1 
     - echo "deployed successfully"
   only:
    - master
