apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-env-crm-content
  namespace: poc-env-crm-content
  labels:
    app: poc-env-crm-content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-env-crm-content
  template:
    metadata:
      labels:
        app: poc-env-crm-content
    spec:
      containers:
      - name: poc-env-crm-content
        image: vapprtech/arrivnow-reactjs:latest
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 1337
