apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-crm-content
  namespace: demo-crm-content
  labels:
    app: demo-crm-content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-crm-content
  template:
    metadata:
      labels:
        app: demo-crm-content
    spec:
      containers:
      - name: demo-crm-content
        image: vapprtech/demo:latest
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 1337