apiVersion: v1
kind: Service
metadata:
  name: crm-content
  namespace: crm-content
  labels:
    app: crm-content
spec:
  type: NodePort
  ports:
  - name: https
    port: 80
    targetPort: 1337
  selector:
    app: crm-content

