apiVersion: v1
kind: Service
metadata:
  name: poc_env_crm-content
  namespace: poc_env_crm-content
  labels:
    app: poc_env_crm-content
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 1337
    targetPort: 1337
  selector:
    app: poc_env_crm-content

