apiVersion: v1
kind: Service
metadata:
  name: demo-crm-content
  namespace: demo-crm-content
  labels:
    app: demo-crm-content
spec:
  type: NodePort
  ports:
  - name: https
    port: 80
    targetPort: 1337
  selector:
    app: demo-crm-content
